server.port=8181
server.servlet.context-path=/producer

spring.application.name=lib-evt-producer-app

# Kafka topic properties
spring.kafka.topic.name=lib-evts-topic
spring.kafka.topic.nombre-partitions=3
spring.kafka.topic.nombre-replicas=1

spring.config.activate.on-profile=nonprod
spring.kafka.producer.bootstrap-servers= 172.30.224.1:9092
#, 172.30.224.1:9093, 172.30.224.1:9094
spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.IntegerSerializer
spring.kafka.producer.value-serializer= org.apache.kafka.common.serialization.StringSerializer 