server.port=8181
server.servlet.context-path=/producer

spring.application.name=lib-evt-producer-app
spring.profiles.active=local
spring.kafka.producer.bootstrap-servers=localhost:9092 
#, localhost:9093, localhost:9094
spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.IntegerSerializer
spring.kafka.producer.value-serializer= org.apache.kafka.common.serialization.StringSerializer 
#spring.kafka.admin.properties.bootstrap-servers=127.0.1.1:9092