server.port=8181
server.servlet.context-path=/producer

spring.application.name=lib-evt-producer-app

# Kafka topic properties
spring.kafka.topic.name=lib-evts-topic
spring.kafka.topic.nombre-partitions=3
spring.kafka.topic.nombre-replicas=1

# Dummy Header of Producer record 
spring.kafka.producer-record.header.key=evt-source
spring.kafka.producer-record.header.value=scanner

spring.config.activate.on-profile=local
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.IntegerSerializer
spring.kafka.producer.value-serializer= org.apache.kafka.common.serialization.StringSerializer 
spring.kafka.producer.properties.acks= 1
spring.kafka.producer.properties.retries= 7
 
spring.kafka.admin.properties.bootstrap-servers=localhost:9092
spring.kafka.admin.properties.retries= 7